import { PrismaClient, VideoKind } from '@prisma/client';
import { pinyin } from 'pinyin-pro';
import { parseTranscript } from '../../src/modules/videos/transcript.util';
import { fetchTimedTranscript } from '../../src/modules/videos/youtube-transcript.util';

/**
 * Video mẫu = clip công khai thật trên YouTube.
 * - Video CÓ phụ đề tiếng Trung → lấy bản chép + MỐC THỜI GIAN THẬT (đồng bộ karaoke),
 *   dịch tiếng Việt do Hanni soạn.
 * - Video KHÔNG có phụ đề → dùng bản chép mẫu (thời gian ước lượng theo nhịp đọc).
 * Video `createdById = null` là nội dung hệ thống → seed lại sẽ làm mới.
 */

const hanOnly = (s: string) => s.replace(/[^\p{Script=Han}]/gu, '');

interface Sample {
  youtubeId: string;
  title: string;
  titleZh: string;
  author: string;
  description: string;
  hskLevel: number;
  kind: VideoKind;
  /** dịch theo thứ tự dòng (khớp phụ đề gốc đã lọc) */
  viByIndex?: (string | null)[];
  /** dịch tra theo chữ Hán của dòng (bỏ dấu câu / latin) */
  viByHan?: Record<string, string>;
  /** dùng khi video không có phụ đề tiếng Trung */
  fallback?: string;
}

const SAMPLES: Sample[] = [
  {
    youtubeId: 'o51Dsn7YTjw',
    title: 'Cuộc sống của Mary',
    titleZh: '玛丽的生活',
    author: 'Mandarin Click',
    description:
      'Truyện HSK 1–2, giọng đọc chậm. Phụ đề đồng bộ theo lời nói (mốc thời gian gốc từ YouTube).',
    hskLevel: 2,
    kind: VideoKind.STORY,
    viByHan: {
      玛丽今年十八岁: 'Mary năm nay mười tám tuổi.',
      她是美国人: 'Cô ấy là người Mỹ.',
      和爸爸妈妈住在北京: 'Sống cùng bố mẹ ở Bắc Kinh.',
      她的爸爸是老师: 'Bố cô ấy là giáo viên,',
      妈妈是医生: 'còn mẹ là bác sĩ.',
      年他们来中国工作: 'Năm 2015 họ đến Trung Quốc làm việc.',
      玛丽和他们一起来中国学习: 'Mary cùng họ đến Trung Quốc học.',
      他们有一只狗: 'Họ có một con chó.',
      小狗很可爱名字叫乐乐: 'Chú chó rất đáng yêu, tên là Lạc Lạc.',
      玛丽很喜欢和它一起玩儿: 'Mary rất thích chơi với nó.',
      他们来中国快六年了: 'Họ đến Trung Quốc gần sáu năm rồi,',
      认识了很多好朋友: 'quen được rất nhiều bạn tốt.',
      他们经常一起吃饭喝茶: 'Họ thường cùng nhau ăn cơm, uống trà.',
      玛丽的爸爸喜欢看书: 'Bố Mary thích đọc sách.',
      妈妈喜欢看电影买东西: 'Mẹ thích xem phim, mua sắm.',
      玛丽喜欢听歌学中文: 'Mary thích nghe nhạc, học tiếng Trung.',
      玛丽会说中文也会写字: 'Mary biết nói tiếng Trung, cũng biết viết chữ.',
      她在大学学习很好: 'Cô ấy học ở đại học rất tốt.',
      同学和老师都很喜欢她: 'Bạn học và thầy cô đều rất quý cô ấy.',
      下个月是妈妈的生日: 'Tháng sau là sinh nhật mẹ.',
      她想给妈妈买一件礼物: 'Cô ấy muốn mua cho mẹ một món quà.',
      但是她没有很多钱: 'Nhưng cô ấy không có nhiều tiền.',
      学校后面有一家饭店: 'Phía sau trường có một nhà hàng.',
      她上午八点去学校学习: 'Buổi sáng tám giờ cô ấy đến trường học,',
      下午四点去饭店工作: 'buổi chiều bốn giờ đi làm ở nhà hàng.',
      一个月后她有钱了: 'Một tháng sau, cô ấy có tiền rồi.',
      她给妈妈买了一件漂亮的衣服: 'Cô ấy mua cho mẹ một bộ quần áo đẹp.',
      给自己买了一本汉语书: 'Mua cho mình một quyển sách tiếng Hán.',
      生日的时候她给妈妈礼物: 'Hôm sinh nhật, cô ấy tặng quà cho mẹ.',
      妈妈看见漂亮的衣服很高兴: 'Mẹ nhìn thấy bộ quần áo đẹp, rất vui.',
      她和玛丽说: 'Mẹ nói với Mary:',
      谢谢你我的女儿: '“Cảm ơn con, con gái của mẹ.',
      妈妈爱你: 'Mẹ yêu con!”',
    },
  },
  {
    youtubeId: 'fbjSH487Hhc',
    title: 'Amber và mèo Tiền Tiền',
    titleZh: '你好，我是 Amber',
    author: 'Comprehensible Chinese',
    description:
      'TPRS siêu cơ bản: câu ngắn, lặp lại nhiều. Phụ đề đồng bộ theo lời nói.',
    hskLevel: 1,
    kind: VideoKind.STORY,
    viByIndex: [
      'Xin chào.',
      'Xin chào, tôi là Amber.',
      'Nó không phải Amber, nó là Tiền Tiền.',
      'Tôi ở nhà, nó không ở nhà.',
      'Nó ở quán bar.',
      'Tôi là Amber phải không?',
      'Phải, tôi là Amber.',
      'Nó là Amber phải không?',
      'Không, nó không phải Amber.',
      'Nó là Beyoncé phải không?',
      'Không, nó cũng không phải Beyoncé.',
      'Nó không phải Amber.',
      'Nó cũng không phải Beyoncé.',
      'Vậy nó là ai?',
      'Tiền Tiền.',
      'Nó là Tiền Tiền.',
      'Tôi có ở nhà không?',
      'Ở nhà, tôi ở nhà.',
      'Tiền Tiền có ở nhà không?',
      'Không, Tiền Tiền không ở nhà.',
      'Tiền Tiền có ở công ty không?',
      'Không, Tiền Tiền không ở công ty.',
      'Tiền Tiền không ở nhà, cũng không ở công ty.',
      'Vậy Tiền Tiền ở đâu?',
      'Ở quán bar, Tiền Tiền ở quán bar.',
      'Tôi thích uống cà phê.',
      'Tiền Tiền không thích uống cà phê.',
      'Nó thích uống rượu.',
      'Tôi uống cà phê ở nhà.',
      'Tiền Tiền uống rượu ở quán bar.',
      'Tôi có thích uống cà phê không?',
      'Thích, tôi thích uống cà phê.',
      'Nó có thích uống cà phê không?',
      'Không thích, nó không thích uống cà phê.',
      'Nó có thích uống rượu không?',
      'Thích, nó thích uống rượu.',
      'Nó có uống rượu ở nhà không?',
      'Không, nó không uống rượu ở nhà.',
      'Nó uống rượu ở quán bar.',
      'Xin chào, tôi là Amber.',
      'Nó không phải Amber, nó là Tiền Tiền.',
      'Tôi ở nhà, nó không ở nhà.',
      'Nó ở quán bar.',
      'Tôi thích uống cà phê.',
      'Nó không thích uống cà phê.',
      'Nó thích uống rượu.',
      'Tôi uống cà phê ở nhà.',
      'Nó uống rượu ở quán bar.',
      'Nó là Lạc Lạc.',
      'Lạc Lạc cũng ở quán bar.',
      'Nó không thích uống cà phê.',
      'cũng không thích uống rượu.',
      'Nó thích uống nước.',
      'Tiền Tiền thích Lạc Lạc.',
      'Nhưng Lạc Lạc không thích Tiền Tiền.',
      'Bạn có thích uống cà phê không?',
      'Tạm biệt, tạm biệt.',
    ],
  },
  {
    youtubeId: '38v1e6QiTUQ',
    title: "Chuyện tình 'gặp 5 lần rồi cưới'",
    titleZh: '我和老公的爱情故事',
    author: 'Lazy Chinese',
    description:
      'Truyện đời thường, giọng chậm rõ: cô gái Trung Quốc và chồng người Mỹ chỉ gặp nhau 5 lần trước khi cưới. Phụ đề đồng bộ theo lời nói.',
    hskLevel: 2,
    kind: VideoKind.STORY,
    viByIndex: [
      'Bây giờ tôi đã kết hôn.',
      'Tôi có một người chồng,',
      'có một đứa con.',
      'Nhưng bạn biết không?',
      'Từ khi quen nhau đến lúc',
      'sinh con, tôi và chồng chỉ gặp nhau 5 lần, đúng vậy, 5 lần.',
      'Có thể bạn thấy rất lạ.',
      'Gì cơ?',
      'Gặp nhau 5 lần là đã có thể cưới nhau, sinh con sao?',
      'Hôm nay tôi sẽ kể chuyện của tôi và chồng.',
      'Bạn đoán xem tôi quen chồng mình như thế nào?',
      'Qua app hẹn hò hay nhờ bạn bè?',
      'Đều không phải, là nhờ em trai của chồng tôi.',
      'Hồi tôi 20 tuổi, tôi đến một bữa tiệc.',
      'Ở bữa tiệc đó,',
      'tôi quen em trai của chồng tôi.',
      'Em trai chồng tôi nhìn thấy tôi,',
      'cậu ấy thấy tôi rất cao.',
      'Tôi cao một mét bảy tư.',
      'Cậu ấy biết, ừm, anh trai mình',
      'rất thích con gái cao.',
      'Nên khi cậu em trai nhìn thấy tôi,',
      'cậu ấy nghĩ anh trai mình chắc sẽ thích tôi.',
      'Thế là,',
      'cậu ấy gửi ảnh tôi cho anh trai.',
      'Anh trai cậu ấy nhìn thấy ảnh tôi.',
      'Bạn nghĩ anh ấy có thích tôi không?',
      'Đúng, anh ấy thích tôi.',
      'Khi nhìn thấy ảnh tôi,',
      'anh ấy đã muốn ở bên tôi.',
      'Vậy lúc đó chúng tôi thật sự đến với nhau chưa?',
      'Chưa, chúng tôi chưa đến với nhau.',
      'Lúc đó anh ấy chưa trở thành bạn trai tôi.',
      'Vì lúc đó tôi đã có bạn trai.',
      'Tôi không cần một bạn trai mới.',
      'Lúc đó tôi và anh ấy chỉ là bạn trên WeChat.',
      'Vậy nếu chỉ là bạn WeChat,',
      'thì làm sao chúng tôi thành người yêu của nhau?',
      'Đó là vì vào năm 2017,',
      'tôi muốn mua một món đồ.',
      'Nhưng món đồ này, ừm, ở Trung Quốc không có.',
      'Nên tôi nhắn WeChat hỏi chồng tôi bây giờ.',
      'Tôi hỏi anh ấy có thể mua giúp tôi món đồ đó,',
      'rồi gửi về Trung Quốc không?',
      'Vì chuyện này,',
      'tôi và anh ấy lại bắt đầu nói chuyện.',
      'Lúc đó tôi có bạn trai không?',
      'Không, tôi không có bạn trai.',
      'Vì tôi đã chia tay bạn trai cũ.',
      'Một tháng sau,',
      'người đàn ông này,',
      'tức là chồng tôi bây giờ,',
      'đi máy bay',
      'bay về Trung Quốc thăm tôi.',
      'Nhưng lần đầu gặp mặt,',
      'không phải chỉ hai chúng tôi,',
      'mà là ba người.',
      'Tại sao?',
      'Vì tôi dẫn theo bạn thân của mình.',
      'Vậy sau bữa ăn,',
      'chúng tôi đã thành người yêu chưa?',
      'Tất nhiên là chưa.',
      'Vì tôi thấy tôi ở Trung Quốc,',
      'anh ấy ở Mỹ,',
      'hai chúng tôi ở cách nhau quá xa.',
      'Hôm đó chồng tôi đã nói,',
      'anh ấy thích tôi.',
      'Nhưng lúc đó tôi không muốn làm bạn gái anh ấy.',
      'Chồng tôi quay lại Mỹ,',
      'nhưng chúng tôi vẫn nói chuyện mỗi ngày.',
      'Nửa năm sau,',
      'tức là 6 tháng sau,',
      'cuối cùng tôi đồng ý,',
      'em có thể làm bạn gái anh.',
      'Tháng 4 năm 2018,',
      'anh ấy từ Mỹ bay về Trung Quốc.',
      'Đây là lần gặp thứ hai của chúng tôi.',
      'Giờ chúng tôi là người yêu rồi!',
      'Chúng tôi cùng đi du lịch Thái Lan.',
      'Bố mẹ hai bên cũng gặp nhau.',
      'Bố mẹ chúng tôi cũng rất vui.',
      'Tháng 12 năm 2018,',
      'chúng tôi gặp nhau lần thứ ba.',
      'Vì sao lại gặp nhau?',
      'Vì chúng tôi sắp đính hôn.',
      'Cuối cùng chúng tôi cũng sắp đính hôn.',
      'Cả hai đều thấy mình đã tìm được đúng người.',
      'Nhưng lần gặp thứ ba rất ngắn,',
      'chỉ có hai tuần,',
      'tức là hai tuần lễ.',
      'Rồi anh ấy lại phải về Mỹ tiếp tục làm việc.',
      'Giờ là lần gặp thứ tư.',
      'Lần gặp thứ tư là vào năm 2019.',
      'Chúng tôi kết hôn rồi!',
      'Cuối cùng chúng tôi cũng cưới nhau.',
      'Chúng tôi cưới ở Trung Quốc.',
      'Nhưng tôi quyết định,',
      'tôi sẽ cùng anh ấy sang Mỹ sống.',
      'Nên tôi ở Trung Quốc, ừm, chờ visa Mỹ.',
      'Nhưng tháng 12 năm 2019,',
      'lúc đó bạn có biết đã xảy ra chuyện gì không?',
      'Dịch bệnh bùng phát.',
      'Lúc đó đi nước khác rất khó.',
      'Chồng tôi muốn về Trung Quốc cũng rất khó.',
      'Lúc đó,',
      'có lẽ mọi người đều nghĩ, ừm,',
      'dịch này sẽ nhanh chóng kết thúc.',
      'Nhưng vì dịch bệnh này,',
      'suốt ba năm chúng tôi không thể gặp nhau.',
      'Trong ba năm đó,',
      'tôi và chồng tôi,',
      'suy nghĩ của chúng tôi cũng thay đổi.',
      'Chúng tôi thấy có người vì dịch bệnh',
      'mà qua đời, nên lúc đó chúng tôi thấy rằng,',
      'được ở bên người thân là quan trọng nhất.',
      'Nên chồng tôi quyết định rời Mỹ,',
      'quay về Trung Quốc,',
      'rồi chúng tôi sống cùng nhau.',
      'Chồng tôi đã về Trung Quốc.',
      'Đây là lần gặp thứ năm của chúng tôi.',
      'Đúng vậy, lần gặp thứ năm.',
      'Chúng tôi cùng đi du lịch 6 tháng, 6 tháng.',
      'Rồi vào tháng 9 năm 2023,',
      'tôi có em bé đầu lòng của chúng tôi.',
      'Đúng, tôi',
      'mang thai.',
      'Em bé của chúng tôi chào đời năm 2024.',
      'Đây chính là chuyện của tôi và chồng, từ',
      'quen nhau đến kết hôn rồi sinh con.',
      'Còn các bạn thì sao?',
      'Bạn và chồng/vợ mình đã quen nhau thế nào,',
      'đến với nhau ra sao?',
      'Bạn có gặp nhau 5 lần rồi cưới và sinh con không?',
      'Nhớ để lại bình luận cho tôi biết nhé!',
    ],
  },
  {
    youtubeId: 'sfmInzCQ8-E',
    title: 'Tái ông thất mã',
    titleZh: '塞翁失马',
    author: 'Blabla Chinese',
    description:
      "Ngụ ngôn kinh điển 'Tái ông thất mã, yên tri phi phúc' kể theo lối TPRS siêu cơ bản: câu ngắn, lặp nhiều. Phụ đề đồng bộ theo lời nói.",
    hskLevel: 1,
    kind: VideoKind.STORY,
    viByIndex: [
      'Ngựa của ông chạy mất rồi!',
      'Ngựa của ông chạy mất rồi!',
      'Ngựa của ông chạy mất rồi!',
      'Chạy mất rồi!',
      'Người này là một ông lão.',
      'Chào ông, chào ông lão.',
      'Người này không phải ông lão.',
      'Amber không phải ông lão.',
      'Người này là ông lão, ông lão.',
      'Người này cũng là ông lão, ông lão, ông lão.',
      'không phải ông lão.',
      'Ông lão này là bố của người này.',
      'Người này là con trai của ông lão.',
      'Còn ông lão này thì sao?',
      'Ông lão này là ai?',
      'Ông lão này là hàng xóm của ông lão kia, hàng xóm.',
      'Đây là nhà của họ.',
      'Đây là nhà của ông lão.',
      'Ông ấy là hàng xóm của họ, hàng xóm.',
      'Ông lão này có một người con trai.',
      'Ông lão này có một con ngựa.',
      'Ông lão có một con ngựa.',
      'Ông lão rất quý con ngựa này, con ngựa này.',
      'Tôi thích con ngựa này.',
      'Nhưng một hôm,',
      'một hôm,',
      'con ngựa chạy mất.',
      'chạy, chạy, chạy... chạy mất rồi.',
      'Con ngựa chạy mất rồi.',
      'Ông lão nói: "Ồ."',
      'Ngựa chạy mất, được thôi, được thôi, chạy thì chạy.',
      'Nhưng người hàng xóm của ông lão,',
      'hàng xóm của ông,',
      'ông lão kia,',
      'ông ấy sang nhà ông lão.',
      'sang nhà ông ấy.',
      'Ông lão này nói với ông lão kia:',
      'Ngựa của ông chạy mất rồi!',
      'Ngựa của ông chạy mất rồi!',
      'Ngựa của ông chạy mất rồi!',
      'Chạy mất rồi!',
      'Xui quá, xui quá.',
      'Ông mất rồi, ông không còn ngựa nữa, xui thật.',
      'Ông lão nói: "Xui à? Xui à?',
      'Có thể là xui,',
      'có thể là may,',
      'có thể xui, có thể may, ai biết được."',
      'Ông lão kia nói: "May cái gì chứ?"',
      'Tạm biệt, tạm biệt.',
      'Ông lão kia về nhà.',
      'Ông ấy về nhà mình.',
      'Về nhà, ông ấy về nhà rồi.',
      'Một, hai, ba... ba ngày sau,',
      'con ngựa của ông lão quay về.',
      'Ngựa của ông ấy quay về, quay về... quay về rồi.',
      'Không phải một con ngựa quay về,',
      'mà là một, hai... hai con ngựa quay về.',
      'Người hàng xóm sang nhà ông lão.',
      'Người hàng xóm nói:',
      'Ồ, ông có hai con ngựa!',
      'Ồ, ông có hai con ngựa!',
      'May quá, may quá.',
      'Ông lão nói: "May à?',
      'Có thể là may,',
      'có thể là xui,',
      'ai biết được."',
      'Người hàng xóm nói: "Nói gì vậy?',
      'Hai con ngựa mà lại không may à?"',
      'Người hàng xóm về nhà, về nhà rồi.',
      'Nhưng một, hai, ba...',
      'ba ngày sau,',
      'con trai ông lão cưỡi ngựa.',
      'Cậu ấy cưỡi ngựa phi, phi, phi...',
      'rất nhanh, rất nhanh, rất nhanh.',
      'phi, phi, phi...',
      'Con trai ông ấy',
      'ngã, ngã rồi.',
      'Chân con trai ông ấy, chân, chân.',
      'chân của người con trai.',
      'không phải chân ngựa.',
      'Chân người con trai, chân, chân.',
      'Chân người con trai bị thương, bị thương rồi.',
      'Người hàng xóm sang nhà ông lão.',
      'Người hàng xóm nói:',
      'Chân con trai ông',
      'bị thương rồi.',
      'Xui quá, xui quá.',
      'Chân con trai ông bị thương rồi.',
      'Ông lão nói:',
      '"Xui à?',
      'Có thể xui, có thể may,',
      'ai biết được, ai biết được."',
      'Người hàng xóm nói:',
      '"May cái gì chứ?"',
      'Tạm biệt.',
      'Người hàng xóm về nhà, về nhà rồi.',
      'Một ngày, hai ngày, 3 ngày, 4 ngày, 5 ngày, 6 ngày,',
      '7 ngày, 8 ngày... rất nhiều ngày sau,',
      'họ đánh nhau, chiến tranh.',
      'Họ nói: "Ông già rồi, thôi được,',
      'không phải đi, không phải đi.',
      'Ông lão không phải đi lính."',
      '"Còn cậu không già, đi, đi, đi!"',
      'Nhưng',
      'con trai ông lão nói:',
      '"Chân tôi, chân tôi bị thương."',
      'Họ nói: "Được, được,',
      'chân cậu bị thương, thôi được, được rồi.',
      'Không phải đi, không phải đi.',
      'Cậu về nhà đi."',
      'Về nhà, về nhà, về nhà.',
      'Thế là họ... họ đi đánh trận, đánh trận.',
      'Họ chết trận.',
      'Nhưng con trai ông lão không phải đi đánh trận.',
      'Con trai ông lão không chết.',
      'Vì vậy rất nhiều người Trung Quốc nghe chuyện con ngựa của ông lão',
      'là may hay xui?',
      'Nghe câu chuyện này,',
      'rất nhiều người Trung Quốc biết rằng',
      'có thể hôm nay',
      'là xui, là xui,',
      'nhưng có thể sau này lại may, may hay xui ai biết được.',
      'Ông lão nói: "Đúng, đúng."',
      'Nhưng vào blablachinese.com thì chắc chắn là may.',
      'Hê hê, vào đi.',
      'Tạm biệt.',
    ],
  },
  {
    youtubeId: 'O-eW3Kq8UwQ',
    title: 'Tuổi thơ của Đặng Lệ Quân',
    titleZh: '邓丽君的童年',
    author: 'Lazy Chinese',
    description:
      'Chân dung danh ca Đặng Lệ Quân thuở nhỏ: nhà nghèo, mê hát, 14 tuổi đã thành ca sĩ nổi tiếng nhất Đài Loan. Trình độ trung cấp thấp, phụ đề đồng bộ theo lời nói.',
    hskLevel: 3,
    kind: VideoKind.STORY,
    viByIndex: [
      'Bạn từng nghe bài hát này chưa?',
      'Hay là bài này?',
      'Còn bài này thì sao?',
      'Những bài hát này đều của cùng một người.',
      'Nếu bạn có người bạn nói tiếng Trung,',
      'thì chắc chắn bạn từng nghe nhạc của cô ấy.',
      'Có người nói, hễ nơi nào có người Hoa,',
      'thì nhất định có nhạc của cô ấy.',
      'Hôm nay, người tôi muốn giới thiệu chính là Đặng Lệ Quân.',
      'Ngày 29 tháng 1 năm 1953,',
      'Đặng Lệ Quân chào đời tại một làng quê nhỏ ở Đài Loan.',
      'Bố cô là quân nhân.',
      'Bố cô vốn',
      'sống ở tỉnh Hà Bắc, miền bắc Trung Quốc.',
      'Về sau,',
      'bố cô theo quân đội chuyển đến Đài Loan.',
      'Khi đó, vì công việc,',
      'nên',
      'ông đưa cả nhà đến khu "quyến thôn" ở Đài Bắc.',
      'Vậy "quyến thôn" là gì?',
      '"Quyến thôn" là nơi mà thời đó,',
      'nhiều quân nhân đưa gia đình từ Trung Quốc sang Đài Loan.',
      'Chính quyền xây cho họ những căn nhà đơn sơ.',
      'Các quân nhân sống quây quần với nhau.',
      'Nơi đó gọi là "quyến thôn".',
      'Nhà Đặng Lệ Quân rất đông người.',
      'Trong nhà có bố mẹ,',
      'ba người anh trai và một em trai.',
      'Trong năm người con,',
      'Đặng Lệ Quân là con gái duy nhất.',
      'Vì vậy bố mẹ và các anh đều rất mực yêu thương cô.',
      'Nhưng thời đó nhà cô rất nghèo.',
      'Nhà có 7 người,',
      'mà chỉ mình bố đi làm.',
      'Khi ấy, đồ đạc ở Đài Loan ngày càng đắt đỏ.',
      'Tiền của bố thường không đủ tiêu.',
      'Trong nhà,',
      'có lúc đến tiền mua bánh mì, mua gạo cũng không có.',
      'Để sống qua ngày, mẹ thường phải sang hàng xóm vay tiền.',
      'Nhưng khi đó, cô bé Đặng Lệ Quân',
      'là một đứa trẻ rất ngoan.',
      'Cô rất nghe lời, cũng rất hiểu chuyện.',
      'Quan trọng hơn, từ nhỏ cô đã hát rất hay.',
      'Bố họ Đặng rất thích âm nhạc Trung Hoa.',
      'Bản thân ông cũng kéo đàn nhị rất giỏi.',
      'Khi Đặng Lệ Quân mới hai, ba tuổi,',
      'cô chỉ cần nghe một bài hát một lần,',
      'là có thể hát lại được bài đó.',
      'Bố phát hiện con gái hát rất hay,',
      'rất vui, nên những lúc rảnh,',
      'ông vừa kéo đàn nhị vừa hát cùng con gái.',
      'Có một lần,',
      'mẹ dẫn cô bé Đặng Lệ Quân đi ngang qua',
      'một tiệm bánh mì.',
      'Khi đó Đặng Lệ Quân còn rất nhỏ.',
      'Nhìn tiệm bánh thơm ngon,',
      'bụng đói cồn cào, rất thèm ăn.',
      'Nhưng trong túi mẹ không có tiền,',
      'chỉ biết lắc đầu với cô.',
      'Lúc đó, cô bé Đặng Lệ Quân thông minh không khóc.',
      'Cô đi đến trước cửa tiệm bánh,',
      'rồi cất tiếng hát vang.',
      'Giọng hát của cô rất hay.',
      'Ông chủ tiệm bánh',
      'thấy cô bé này thật giỏi,',
      'nên lấy mấy ổ bánh mì to tặng cô.',
      'Cô bé Đặng Lệ Quân',
      'đã dùng giọng hát của mình đổi lấy bánh mì ngon cho nhà.',
      'Về sau, Đặng Lệ Quân đi học, vì nhà nghèo,',
      'nên quần áo và giày dép của cô thường vừa rách vừa cũ.',
      'Có những bộ đồ là của anh trai mặc không vừa nữa,',
      'không mặc được mới nhường lại cho cô.',
      'Đến bữa trưa,',
      'bữa trưa của các bạn khác có thịt có rau,',
      'còn bữa trưa của Đặng Lệ Quân chỉ có cơm trắng và',
      'một chút rau.',
      'Ở trường, vài bạn học phát hiện ra chuyện này.',
      'Vì nhà Đặng Lệ Quân nghèo,',
      'nên họ coi thường cô.',
      'Những bạn này thường không nói chuyện với cô.',
      'Có người còn chê cười cô.',
      'Nhưng cô bé Đặng Lệ Quân rất dũng cảm.',
      'Cô không khóc ở trường,',
      'cũng không về mách bố mẹ.',
      'Vì cô không muốn bố mẹ lo lắng.',
      'Mỗi lần thấy buồn,',
      'cô lại hát thật to trên đường về nhà.',
      'Cô thấy ca hát là người bạn tốt nhất của mình.',
      'Chỉ cần hát lên,',
      'là cô quên hết mọi chuyện buồn.',
      'Vài năm sau, Đặng Lệ Quân lên 10 tuổi.',
      'Khi đó có một cuộc thi hát.',
      'Đặng Lệ Quân 10 tuổi rất muốn tham gia.',
      'Nhưng cô biết mình còn quá nhỏ,',
      'trường sẽ không cho cô đi thi.',
      'Thế là cô không báo với trường,',
      'lén đi thi.',
      'Lúc thi,',
      'mọi người đều nghĩ cô chỉ là một đứa trẻ.',
      'Nhưng khi Đặng Lệ Quân cất tiếng hát,',
      'mọi người đều lặng im lắng nghe.',
      'Bởi giọng hát của cô thật sự quá hay.',
      'Hoàn toàn không giống một đứa trẻ 10 tuổi.',
      'Cuối cùng Đặng Lệ Quân thắng cuộc, giành giải nhất.',
      'Đúng vậy, cô là quán quân.',
      'Câu chuyện của cô xuất hiện cả trên truyền hình lẫn báo chí.',
      'Về sau,',
      'ai cũng biết đến cô bé biết hát này.',
      'Sau khi giành giải nhất,',
      'Đặng Lệ Quân trở nên nổi tiếng.',
      'Khi đó, nhà Đặng Lệ Quân vẫn còn nghèo.',
      'Để đỡ đần bố mẹ, Đặng Lệ Quân 14 tuổi',
      'bắt đầu phụ giúp gia đình.',
      'Ban ngày, cô mặc đồng phục đến trường học.',
      'Đến tối, cô thay bộ đồ đẹp,',
      'đi hát ở nhiều nơi khác nhau.',
      'Thường làm đến rất khuya,',
      '11, 12 giờ mới được về nhà ngủ.',
      'Cô kiếm được tiền,',
      'giúp cuộc sống gia đình khá lên.',
      'Nhưng điều đó lại khiến nhà trường rất không hài lòng.',
      'Vì khi đó trường cho rằng học sinh không nên',
      'đi hát ở bên ngoài.',
      'Nên một hôm,',
      'nhà trường nói với Đặng Lệ Quân và mẹ cô:',
      '"Nếu em tiếp tục đi hát,',
      'không chuyên tâm học hành, thì em phải rời trường ngay."',
      'Đặng Lệ Quân rất buồn.',
      'Vì một bên là ngôi trường cô yêu quý,',
      'một bên là cuộc sống của cả nhà.',
      'Cô thật sự không biết phải làm sao.',
      'Cuối cùng, vì bố mẹ,',
      'cô chọn rời trường,',
      'bắt đầu cuộc đời ca sĩ.',
      'Sau khi nghỉ học, Đặng Lệ Quân',
      'dồn hết thời gian cho công việc và âm nhạc.',
      'Năm 1967, cô ra đĩa hát đầu tiên.',
      'Đĩa hát này được rất nhiều người yêu thích.',
      'Họ thấy giọng hát của cô ngọt ngào, dễ chịu.',
      'Ở rất nhiều nơi,',
      'đều nghe được nhạc của Đặng Lệ Quân.',
      'Cô gái từng bị bạn bè coi thường,',
      'không có tiền mua bánh mì,',
      'đã nỗ lực dùng giọng hát hay của mình để thay đổi',
      'cuộc đời mình.',
      'Cô trở thành ca sĩ nổi tiếng nhất Đài Loan.',
      'Mà năm đó cô mới chỉ 14 tuổi.',
      'Nhưng bạn biết không?',
      'Thành công ở Đài Loan mới chỉ là khởi đầu nhỏ bé.',
      'Đặng Lệ Quân khi đó',
      'chưa biết rằng sau này mình sẽ được nhiều người biết đến hơn nữa.',
      'Giọng hát của cô sẽ vang đến nhiều quốc gia hơn,',
      'được nhiều người yêu thích hơn.',
      'Cô sẽ gặp thêm nhiều người và câu chuyện thú vị.',
      'Tập sau, tôi sẽ kể cho bạn nghe sau khi ra nước ngoài,',
      'cô quen một người vô cùng giàu có.',
      'Hai người suýt nữa thì kết hôn.',
      'Vậy vì sao họ lại không cưới nhau?',
      'Mời bạn đến kênh Lazy Chinese xem',
      'thêm nhiều câu chuyện về cô.',
      'Nếu bạn thích câu chuyện hôm nay,',
      'đừng quên để lại bình luận cho tôi nhé.',
      'Hẹn gặp lại ở video sau, tạm biệt!',
    ],
  },
];

export async function seedVideos(prisma: PrismaClient): Promise<void> {
  await prisma.video.deleteMany({ where: { createdById: null } });

  let synced = 0;
  let count = 0;
  for (const s of SAMPLES) {
    const timed = await fetchTimedTranscript(s.youtubeId).catch(() => []);

    const lines =
      timed.length >= 3
        ? timed.map((tl, i) => ({
            index: i + 1,
            startMs: tl.startMs,
            zh: tl.zh,
            pinyin: pinyin(tl.zh, { toneType: 'symbol', nonZh: 'consecutive' }),
            pinyinNum: pinyin(tl.zh, { toneType: 'num', nonZh: 'consecutive' }),
            vi: s.viByIndex?.[i] ?? s.viByHan?.[hanOnly(tl.zh)] ?? null,
          }))
        : parseTranscript(s.fallback ?? '');

    if (lines.length < 3) {
      console.log(`  ⚠ Bỏ qua ${s.youtubeId}: không lấy được bản chép`);
      continue;
    }
    if (timed.length >= 3) synced += 1;
    count += 1;

    await prisma.video.create({
      data: {
        youtubeId: s.youtubeId,
        title: s.title,
        titleZh: s.titleZh,
        description: s.description,
        hskLevel: s.hskLevel,
        kind: s.kind,
        author: s.author,
        sentenceCount: lines.length,
        thumbnailUrl: `https://i.ytimg.com/vi/${s.youtubeId}/hqdefault.jpg`,
        lines: { create: lines },
      },
    });
  }
  console.log(
    `  ✓ ${count} video mẫu (${synced} có phụ đề đồng bộ theo lời nói)`,
  );
}
